### ISSUE TITLE
Poprawki

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#52]
- [x] Brak polskich tekstów.  Na stronie głównej: "Meetings", "Show all events", "Show all projects", "users registered on forum" itp.  "Got idea for app?" na innych -> "Got an idea for an app?" swoją drogą powinno być, ale copy to jeszcze później dopracujemy
- [x] Brak tłumaczeń pozycji w menu górnym (a Contact np. przetłumaczyłem)
- [x] Na głównej: "citylabs" zamieniamy na "local meetups" / "lokalnych spotkań"
- [x] W Kontakt (oraz wszędzie gdzie są ikonki ludzi) niech się wyświetla gravatar jak nie ma ustawionego profilowego; jak nie ma gravatara to niech wyświetla anonimową postać (http://kodujdlapolski.pl/wp-content/uploads/2014/12/searchinf.jpg) (jak potrzebny większy rozmiar to pytaj Arka)
- [x] Kontakt: powinna być większa czcionka, bo nic nie widać
- [x] Brygada: jakieś zło się dzieje (stopka zasłania cały ekran): http://koduj.dev.inovia.pl/cities/wroclaw/  http://koduj.dev.inovia.pl/cities/warszawa/  także na projektach: http://koduj.dev.inovia.pl/projects/pola-zabierz-ja-na-zakupy-4/
- [x] http://koduj.dev.inovia.pl/spotkania/ nazwy spotkań z prawej sortowane alfabtycznie
- [x] "Link do forum" może być w końcu na liście linków, bo i tak różnie będziemy obsługiwać te linki zależnie od zawartości
- [x] Niech do listy linków oprócz Nazwa oraz Adres dojdzie jeszcze flaga "Embeduj" domyślnie zaznaczona na Tak (jak jest wyłączona to niech dany link nie będzie rozwijany w postaci widgetu)
- [x] Github owner / Github name - usunąć te pola na rzecz przetwarzania linków po kolei
- [x] Kategoryzacja projektów: czy można by połączyć Technologie i Status w jedno drzewo kategorii? Fajnie jakbym mógł dodawać nowe (np. Dla kogo? -> Dla miast, dla org. pozarząodwych) jak będę miał potrzebę. 
- [x] Profilowe członków zespołu projektowego: standardowy wymiar + marginesy - http://koduj.dev.inovia.pl/projects/wysadz-ulice/  także na brygadzie: http://koduj.dev.inovia.pl/cities/poznan/
- [x] Na stronie partnerów nie powinna się pojawiać stopka z logami partnerów: http://koduj.dev.inovia.pl/partnerzy/
- [x] Normalizacja wymiarów wszystkich logo na http://koduj.dev.inovia.pl/partnerzy/ (Hackerspace na szerokość wydaje się ok na tej rozdzielczości co ja mam), ale żeby dać tu max szerokośc i max wysokość (np. 300x200) + skalowanie do niej
- [x] Gdy ktoś nie uczestniczy w projektach to niech ta sekcja nie będzie widoczna na blogu http://koduj.dev.inovia.pl/author/piotr/ (podobnie sekcja Posts gdy nie ma wpisów)
- [x] Użytkownik o poziomie dostępu "Lider projektu": nie mogę go wybrać jako autora Projektu już stworzonego, a powinienem móc; powinien mieć prawo do tworzenia wpisów na blogu bez akceptacji (teraz jest wymagana akceptacja)
- [x] Użytkownik o poziomie dostępu Autor: nie powinien móc tworzyć projektów, partnerów i spotkań (teraz może) (czy można szybko zakodować, żeby mu się te zakładki nie wyświetlały w menu? wtedy też Liderowi projektu usunąć wyświetlanie Spotkań)
- [x] Statystyki: liczba pomysłów - Statystyki na stronie głównej powinny się komunikować z API forum (Discourse); pomysły zgłoszone na projekty = [liczba wątków z kategorią pomysł](https://forum.kodujdlapolski.pl/c/pomysly) #11
- [x] Błąd gdy nie jest ustawiony "obrazek wyróżniający" na wpisie - http://koduj.dev.inovia.pl/wpis-autora/
- [x] Na stronie miast wszystkich http://koduj.dev.inovia.pl/spotkania/ kafelek CtA powinien mieć copy "Do you want to organize meetups in your city? Write to us!" i link mailto: kontakt@kodujdlapolski.pl; design tu #23 
- [x] Stopka partnerów - #20 
- [x] Na głównej stronie na zdjęciu - pogrubić "Koduj dla Polski" w tekście "jest społecznością"... Usunąć czerwony link "Dołącz do nas" stamtąd
- [x] "Blog powinien pojawić się także na stronie brygad [wszystkich, ale też pojedynczej (3 posty + "See all" - przyp. Krzysiek], nad partnerami, w podobnym układzie jak na stronie głównej. Powinny się pojawiać posty tylko z jednej wybranej kategorii odpowiadającej miastu." #14 
- [x] Facebook logo u góry na równi z banerem Fundacji (jak w #13 tylko kwadratowe logo https://www.facebookbrand.com/)
- [x] Endpointy dla Code for All API #10 
- [x] Extra rzecz: aby w filtrach projektów wyświetlały się też miasta; Usuń proszę też to domyślne filtrowanie po 'aktywnych' projektach
- [x] Logowanie poprzez email zamiast nazwy użytkownika #44
- [x] Zdjęcie w poście na blogu powinno być obowiązkowe, żeby nie robiły się sytuacje jak  teraz http://koduj.dev.inovia.pl/blog/ przez nieuwagę
- [x] Strona główna, linkowanie statystyk (ikona +liczba + tekst powinny być objęte linkiem)
  - ilość userów na forum powinna linkować do https://forum.kodujdlapolski.pl
  - pomysły powinny linkować do  https://forum.kodujdlapolski.pl/c/pomysly
  - local events powinien linkować do mapki polski (Spotkania)
  - project powinno linkować do listy projektów
- Wysłanie wiadomości z formularza
  - [x] Po wysłaniu wyświetla się "Success message". Powinno być "Message sent. Copy of it went to your mailbox." / "Wiadomość została wysłana wraz z kopią na twój adres."

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon zajrzyj proszę na stronę nową. Masz jakieś uwagi do layoutów? 

W szczególności zajrzyj na:
- brygadę pojedynczą http://koduj.dev.inovia.pl/cities/poznan/
  - czy nie wyrównać meetings do banera (wstawię niższy swoją drogą)
  - czy meetings nie podrasować jakoś wyglądu
  - kafelek do FB wygląda trochę sucho, jakieś tło w niego wrzucimy tak jak na meetup?
  - czy podział na sekcje (Coordinators, Members, Partners) jest wizualnie ok?
- projekt pojedynczy: http://koduj.dev.inovia.pl/projects/wysadz-ulice/
  - czy profilowe członków nie za małe
  - czy partnerzy wizualnie spoko rozdzieleni
  - czy "see also" nie powinno się zrównać z banerem?

**Comment by pkliks** [comment]
@KrzysztofMadejski 

>  Brak polskich tekstów. Na stronie głównej: "Meetings", "Show all events", "Show all projects", "users registered on forum" itp. "Got idea for app?" na innych -> "Got an idea for an app?" swoją drogą powinno być, ale copy to jeszcze później dopracujemy
Tu musimy najpierw wprowadzić po angielsku te hardcoded, taki wymóg pluginu do obsługi języków, także przygotuj listę tych tekstów w obu językach i pozmieniam.

> Brak tłumaczeń pozycji w menu górnym (a Contact np. przetłumaczyłem)
Wygląd->Menu i tam synchronizuj menu pomiędzy językami, wtedy to zacznie działać.

**Comment by pkliks** [comment]
@ArekSoldon potrzebny jest większy ten blank avatar: http://kodujdlapolski.pl/wp-content/uploads/2014/12/searchinf.jpg (105px na 105px minimum)

**Comment by KrzysztofMadejski** [comment]
@pkliks - Teksty pl/en  są tutaj: https://github.com/epforgpl/web-kodujdlapolski.pl/issues/53

Ad. autor: ok! Czyli z roli "Project leader" nie korzystamy? Liderom projektów ustawiam rolę 'Autor' i ustawiam ich jako autorów projektu, tak?
![kdp-lider](https://cloud.githubusercontent.com/assets/849975/12873347/b434af66-cdba-11e5-8caf-b51387bdd991.PNG)

**Comment by pkliks** [comment]
@KrzysztofMadejski Sorry, nie zauważyłem że ich tam nie listuje, myślałem, że w ogóle nie miałeś tej listy. Przyjrzę się temu

**Comment by KrzysztofMadejski** [comment]
Możemy też zrobić tak, że włączymy "projekt liderów" w "autorów". Trochę mniej kontroli, ale do przeżycia jakby były problemy z rozdzieleniem tych praw dostępu.

**Comment by ArekSoldon** [comment]
![avatar](https://cloud.githubusercontent.com/assets/3994690/12875490/ff879ea2-cdeb-11e5-8027-094fcbc73a97.png)

**Comment by ArekSoldon** [comment]
brygadę pojedynczą http://koduj.dev.inovia.pl/cities/poznan/
czy nie wyrównać meetings do banera (wstawię niższy swoją drogą)
- tak wyrównajmy

czy meetings nie podrasować jakoś wyglądu
kafelek do FB wygląda trochę sucho, jakieś tło w niego wrzucimy tak jak na meetup?

- dodany poniżej

czy podział na sekcje (Coordinators, Members, Partners) jest wizualnie ok? #25

- mogli by coordinators być tez w 3 kolumnach jak to poniżej :)  


projekt pojedynczy: http://koduj.dev.inovia.pl/projects/wysadz-ulice/
czy profilowe członków nie za małe

- nie, raczej są ok

czy partnerzy wizualnie spoko rozdzieleni

- tak

czy "see also" nie powinno się zrównać z banerem?

- tak, zrównajmy :) 
![meetups](https://cloud.githubusercontent.com/assets/3994690/12879395/88888806-ce32-11e5-96a0-4f95e8332590.png)
![fb](https://cloud.githubusercontent.com/assets/3994690/12879396/88c793e8-ce32-11e5-9748-84a2f05e80eb.png)

**Comment by pkliks** [comment]
@KrzysztofMadejski 
>Kategoryzacja projektów: czy można by połączyć Technologie i Status w jedno drzewo kategorii? Fajnie jakbym mógł dodawać nowe (np. Dla kogo? -> Dla miast, dla org. pozarząodwych) jak będę miał potrzebę.

Opcja dodana, tylko teraz trzeba jeszcze raz w ramach Filtrów pooznaczać projekty. Jak będzie gotowe daj znać schowam te stare

**Comment by pkliks** [comment]
@KrzysztofMadejski Zerknij czy poziom dostępów dla autor i project leader jest teraz ok

**Comment by KrzysztofMadejski** [comment]
- Poziom dostępu dla autora śmiga!
- [ ] Project leader powinien móc też tworzyć partnerów
- [ ] Gdy brak partnerów w projekcie to sekcja nie powinna się pokazywać (np. http://koduj.dev.inovia.pl/projects/wizualizacja-budzetu-lodzi/)
- [ ] Loga partnerów w projekcie i w brygadzie wyrównane do środka pionowo, jeżeli są bez opisów (tak jak na głównej) (nie są wyrównani np. na http://koduj.dev.inovia.pl/projects/kalendarz-wydarzen/)
- [ ] Na głównej pod projektami mi się jakiś dziwny border wyświetla, ten `<hr>` był na projekcie? Nie lepiej byłoby bez niego?
  
![kdp-glowna-proj](https://cloud.githubusercontent.com/assets/849975/12913728/c491e420-cf20-11e5-9148-f21d2d72e003.PNG)

**Comment by pkliks** [comment]
@KrzysztofMadejski 
> Na głównej pod projektami mi się jakiś dziwny border wyświetla, ten <hr> był na projekcie? Nie lepiej byłoby bez niego?

Był, mi też tak średnio pasuje, wywaliłem.

**Comment by KrzysztofMadejski** [comment]
Ustawiłem Filtry, możesz usunąć `Technologia` i `Status projektu` jako osobne kategorie.

**Comment by pkliks** [comment]
>Jakiś zabłąkany pin przy Blogu się pojawił na http://koduj.dev.inovia.pl/spotkania/ 

To jest to: "Spotkanie Autora" ono nie ma ustawionych pozycji, nie będzie?

**Comment by KrzysztofMadejski** [comment]
A sorki, to usuwam.

**Comment by KrzysztofMadejski** [comment]
- [ ] @ArekSoldon kategorie bloga się zlewają, dobrze byłoby miasta (które są pod spotkaniami) jakoś wyróżnić i je zblokować obok siebie (teraz się przeplatają z innymi kategoriami)
      , propozycja: 
![blog-kategorie](https://cloud.githubusercontent.com/assets/849975/12946130/7623af44-cff2-11e5-9c05-4d23bcebe927.PNG)
- [ ] Nie wyświetla się profilowe autora, jeżeli pochodzi z gravatara na http://koduj.dev.inovia.pl/ruszyly-spotkania-koduj-dla-polski-w-trojmiescie/

**Comment by ArekSoldon** [comment]
Hmmm, ale to chyba inaczej, może bym zrobił inaczej, nie dawał bym kategorii spotkania jako tako... tylko zostwił miasta....

**Comment by pkliks** [comment]
@KrzysztofMadejski 
> Embeddowanie linków z SlideShare (chyba nie można przejść automatycznie z http://www.slideshare.net/epforgpl/tristar-eye-status-03022016 na http://www.slideshare.net/slideshow/embed_code/key/JyyzOgmZmD302t, który można w src wrzucić) - jak to rozwiązać? Dodać embed code jako osobne pole?

To już jest od wtorku wdrożone, przykład: http://koduj.dev.inovia.pl/projects/tristar-eye/ Natomiast problem, o którym piszesz prawdopodobnie będzie trzeba tak rozwiązać przy prezentacji z Google

**Comment by KrzysztofMadejski** [comment]
Tak, Filtry się zmieniły w międzyczasie. Niech teraz losuje z kategorii 'Status prac -> Aktywny rozwój'

**Comment by KrzysztofMadejski** [comment]
Zebrane poprawki od liderów

@ArekSoldon 
- [ ] Na pojedynczym projekcie dać gdzieś (pod tekstem) przycisk "Skontaktuj się z koordynatorem" / "Contact project leader" (funkcjonalnie też formularz, tak jak Dołącz jako)
- [ ] Na pojedynczym projekcie wyświetlać wartości kategorii; Podobnie to robiliśmy w [TranspaenCEE (technology)(topics)](http://transparencee.org/project/mycountry/); np. 
```
Status projektu: rozwój
Dedykowany: dla miast, dla watchdogów
itd.
```
- [ ] logo fundamentu z ekstra wiadomością (na mailu info)
- [ ] czy nie dać cienia pod górnym menu, gdy się zwija przy scrollowaniu (na pewno wyrównać wybór języka)
   ![shadow](https://cloud.githubusercontent.com/assets/849975/13049316/67419628-d3ec-11e5-99ed-924f9071ee74.PNG)


@pkliks:
- [ ] Na stronie głównej: "6 lokalnych spotkań" -> "6 lokalnych grup"
- [ ] wyrównanie avatarów do góry wzg. tekstu na liście członków
  ![kdp-top](https://cloud.githubusercontent.com/assets/849975/13046573/d1c23e7a-d3d9-11e5-881c-111bb86123cf.PNG)
- [ ] na stronie brygady najpierw projekty, później koordynatorzy, członkowie, blog ("Jakbym chciał dołączyć do lokalnej grupy/projektu to bardziej mnie interesuje co grupa robi, a mniej pełna lista osób które do grupy należą"
- [ ] na stronie brygady pl, tłumaczenie "Members" -> "Członkowie"
- [ ] W filtrach na liście projektów dodałem "Dołącz jako" (łatwiej ludzie mogą znaleźć projekty, w które mogą się zaangażować). Wartości kopiowałem z listy otwartych pozycji. Na pojedynczym projekcie przestawmy wyświetlanie "Dołącz jako" biorąc dane z wartości tej kategorii, zamiast pustych oznaczeń osób na liście członków
- [ ] Na stronie głównej "Coming events" -> "Upcoming events"
- [ ] Stopka na głównej w wersji angielskiej nie wyświetla partnerów (niech wyświetla tych samych co w polskiej wersji)
- [ ] Guzik na liście wydarzeń wyśrodkowany
  ![ms1](https://cloud.githubusercontent.com/assets/849975/13049232/bc3a657a-d3eb-11e5-8ffd-6bfb94e6ae23.png)
- [ ] Jak na głównej stronie wybrałem 5 projektów do wyświetlenia, to dolosował jeszcze 6 i jest ich strasznie dużo teraz: http://koduj.dev.inovia.pl/
- [ ] Na głównej powinien w końcu dolosowywać (do wybranych) projekty z kategorii `Status prac -> aktywny rozwój`
- [ ] Na głównej stronie nie przetłumaczone "Got idea for app? Submit it", powinno być ""Masz pomysł na aplikację? Zgłoś go!" / "Got an idea for an app? Tell us!" 
- [ ] Powyższe (idea for app) także na stronie brygady
- [ ] Strona miasta – jak nie ma partnerów to nie dawać nagłówka "Partnerzy" (np. tu http://koduj.dev.inovia.pl/cities/warszawa/)
- [ ] Nie przetumaczone opisy na stronie Miasta (np. http://koduj.dev.inovia.pl/cities/warszawa/)
  - "Discuss on Facebook" -> "Dyskutuj na Facebook"
  - "Sign up on Meetup" -> "Śledź spotkania na Meetup"
- [ ] Na stronie Miasta - wyrzucić etykietki spod nazwisk organizatorów ("Local leader")
- [ ] W kilku miejsach posty źle się układają (http://koduj.dev.inovia.pl/category/spotkania/warszawa/, http://koduj.dev.inovia.pl/author/michal_szkodzinski/)
  ![aa](https://cloud.githubusercontent.com/assets/849975/13049792/ac558bc2-d3ef-11e5-80ff-9163593e626a.png)
- [ ] Na stronie miasta powtarzają się członkowie, jeżeli powtarzają się w projektach (np. "Kuba Lipiński na http://koduj.dev.inovia.pl/cities/warszawa/); powinni występować raz
- [ ] Dziwny margines na liście kategorii, gdy się wybierze jakąś kategorię (np. http://koduj.dev.inovia.pl/category/blog/)
  ![kdp-blog](https://cloud.githubusercontent.com/assets/849975/13049898/626f7b0c-d3f0-11e5-8e15-8c6e00e0624a.PNG)

**Comment by pkliks** [comment]
@KrzysztofMadejski 
>Stopka na głównej w wersji angielskiej nie wyświetla partnerów (niech wyświetla tych samych co w polskiej wersji)

Nie wszyscy są dodani w wersji angielskiej. Edycja partnerów w stopce znajduje się w głównym menu Ogólne. W górnym pasku znajduje się zmiana języka który się edytuje.

**Comment by KrzysztofMadejski** [comment]
- [ ] Jeszcze wyświetlanie avatarów organizatorów: http://koduj.dev.inovia.pl/cities/gop-katowice/ (Ania Krawczyk raz ok, raz brakuje)
- [ ] I tu Wojtka coś wydłużyło: http://koduj.dev.inovia.pl/cities/poznan/
- [ ] Embeddowanie właściwego linka z forum, bo teraz są wszędzie gry charytatywne

RWD:
- [ ] Na stronie brygady możemy dać najbliższe spotkania zaraz pod zdjęciem? I wywalić listę członków całkowicie.
- [ ] Na stronie bygady nagłówek "Blog" takim samym stylem jak "Członkowie" itp., bo teraz jest mały (to też na desktop)
- [ ] Na głównej: wywalmy statystyki (cyferki + ikonki); najistotniejsze z nich są spotkania/lokalne grupy i te już się wyświetają na starcie
- [ ] Na stronie brygady opisy projektów nachodzą na siebie (u mnie prawa szersza) -choc raz mi się poprawnie po wyjsciu/wejsciu wyrównało. Na stronie projektów wszystkich  także.
  ![screenshot_2016-02-17-22-53-03](https://cloud.githubusercontent.com/assets/849975/13126547/27625188-d5cb-11e5-9c53-38da02a6d892.png)

**Comment by ArekSoldon** [comment]
![screen-shot-2016-02-17-at-23 04 28](https://cloud.githubusercontent.com/assets/3994690/13126807/58b4c83c-d5cc-11e5-8c68-0314b96fb30b.jpg)

ok, dodajmy cień pod menu... @pkliks dodasz jakiś standardowy?

**Comment by pkliks** [comment]
> I tu Wojtka coś wydłużyło: http://koduj.dev.inovia.pl/cities/poznan/

tu by się przydało żebyście wrzucali zdjęcia wykadrowane w kwadrat

**Comment by KrzysztofMadejski** [comment]
- [ ] zamiast "Program Fundacji ePaństwo" dać "Społeczność to fundament" (podsyłam Kliks na mail)

Zdjęcia jak WP słabo wykadruje to można poprawiać, ale każde kadrować to strasznie dużo pracy. A przecież w WP można zadać, aby sam kadrował.

**Comment by pkliks** [comment]
>Na stronie brygady opisy projektów nachodzą na siebie (u mnie prawa szersza) -choc raz mi się poprawnie po wyjsciu/wejsciu wyrównało. Na stronie projektów wszystkich także. 

jaki system/przeglądarka?

**Comment by KrzysztofMadejski** [comment]
com.android.browser 4.4.4-93cb...

**Comment by KrzysztofMadejski** [comment]
Wartości kategorii wklejajmy w projekcie pod tekstem jego opisu, nad "Skontaktuj się z koordynatorem" w postaci nagłówek strongiem:

![kdp-kaegorie](https://cloud.githubusercontent.com/assets/849975/13144117/d53abbd8-d648-11e5-8032-d29ea236b688.PNG)

**Comment by KrzysztofMadejski** [comment]
Uff ;-)
